public enum State 
{
		PLAYING, PLAYER_ONE_FIN, PLAYER_TWO_FIN, PLAYER_THREE_FIN, PLAYER_FOUR_FIN, PLAYER_ONE_TWO_FIN, PLAYER_ONE_THREE_FIN, 
		PLAYER_ONE_FOUR_FIN, PLAYER_TWO_THREE_FIN, PLAYER_TWO_FOUR_FIN, PLAYER_THREE_FOUR_FIN, PLAYER_ONE_TWO_THREE_FIN,
		PLAYER_ONE_TWO_FOUR_FIN, PLAYER_ONE_THREE_FOUR, PLAYER_TWO_THREE_FOUR, ALL_PLAYERS_FIN
}
